### ISSUE TITLE
[MRESOLVER-325] [REGRESSION] Suddenly seeing I/O errors under windows aborting the build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#1001]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** opened **[MRESOLVER-325](https://issues.apache.org/jira/browse/MRESOLVER-325?redirect=false)** and commented

If one runs a build that otherwise works fine on 3.8.x with 3.9 we now get the following exception (full output can be found here https://github.com/eclipse-platform/eclipse.platform/actions/runs/4211467991/jobs/7309831666):

```java
Error: 5.889 [ERROR] Internal error: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories.15650462061630955031.tmp -> C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories.15650462061630955031.tmp -> C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:108)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories.15650462061630955031.tmp -> C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories
    at org.eclipse.aether.internal.impl.DefaultTrackingFileManager.update (DefaultTrackingFileManager.java:121)
    at org.eclipse.aether.internal.impl.EnhancedLocalRepositoryManager.addRepo (EnhancedLocalRepositoryManager.java:274)
    at org.eclipse.aether.internal.impl.EnhancedLocalRepositoryManager.addArtifact (EnhancedLocalRepositoryManager.java:252)
    at org.eclipse.aether.internal.impl.EnhancedLocalRepositoryManager.add (EnhancedLocalRepositoryManager.java:225)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.evaluateDownloads (DefaultArtifactResolver.java:680)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:592)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:478)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:278)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:255)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:296)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:197)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:413)
    at org.apache.maven.repository.legacy.LegacyRepositorySystem.resolve (LegacyRepositorySystem.java:332)
    at org.eclipse.tycho.osgi.configuration.MavenDependenciesResolverConfigurer.resolve (MavenDependenciesResolverConfigurer.java:104)
    at org.eclipse.tycho.core.shared.MavenDependenciesResolver.resolve (MavenDependenciesResolver.java:60)
    at org.eclipse.tycho.core.resolver.MavenTargetDefinitionContent.<init> (MavenTargetDefinitionContent.java:262)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContentWithExceptions (TargetDefinitionResolver.java:179)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContent (TargetDefinitionResolver.java:110)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.resolveFromArguments (TargetDefinitionResolverService.java:90)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent (ConcurrentHashMap.java:1708)
    at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.getTargetDefinitionContent (TargetDefinitionResolverService.java:65)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.resolveTargetDefinitions (TargetPlatformFactoryImpl.java:214)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:164)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:137)
    at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:88)
    at org.eclipse.tycho.p2resolver.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform (ReactorRepositoryManagerImpl.java:61)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.computePreliminaryTargetPlatform (P2DependencyResolver.java:202)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:130)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$2 (TychoMavenLifecycleParticipant.java:256)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.SpinedBuffer$1Splitr.forEachRemaining (SpinedBuffer.java:364)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.ForEachOps$ForEachTask.compute (ForEachOps.java:290)
    at java.util.concurrent.CountedCompleter.exec (CountedCompleter.java:754)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:373)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec (ForkJoinPool.java:1182)
    at java.util.concurrent.ForkJoinPool.scan (ForkJoinPool.java:1655)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1622)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:165)
```

---

**Affects:** 1.9.4

**Issue Links:**
- [MRESOLVER-329](https://issues.apache.org/jira/browse/MRESOLVER-329) Make IO in DefaultTrackingFileManager more robust
 (_**"is fixed by"**_)
- [MRESOLVER-331](https://issues.apache.org/jira/browse/MRESOLVER-331) Make DefaultTrackingFileManager write directly to tracking files
 (_**"is fixed by"**_)
- [MNG-7705](https://issues.apache.org/jira/browse/MNG-7705) Sporadic failures on multiple builds sharing the same local repo when writing the .lastUpdated file

- [MRESOLVER-372](https://issues.apache.org/jira/browse/MRESOLVER-372) Sporadic AccessDeniedEx on Windows

0 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

I think maybe a (temporary) solution would be to not handle I/O errors fatal here... if the index file can't be updated, the worst that can happen would be that it is retried next time, so maybe worth a warning, but nothing that should completely kill the build!

On the long term, the code should perform file-locking here, if I look at https://github.com/apache/maven-resolver/blob/master/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTrackingFileManager.java the update method is prone to many race-conditions, e.g. the file might be modified after it was read (in that case previous updates are overwritten).

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No, the `DefaultTrackingFileManager` won't be subject to any internal locking. The locking is and must be done by the locking sync context, we have explicitly removed it since it was doing double locking. Looking at the exception this is a Windows issue where another process is trying to access/modify the file. There must be a bug somewhere, or it is a runner issue.

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

>  Looking at the exception this is a Windows issue where another process is trying to access/modify the file. 

As i wrote in the title, yes its is windows, and no there is no other process, this is running on a Github Action runner with only mvn but in a -T1C parallel build configuration you can see the full build output including the command that is running here:

https://github.com/eclipse-platform/eclipse.platform/actions/runs/4211467991/jobs/7309831666):

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Just checked the source code, all calls to the Manager are fully wrapped in sync context.

[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi), please follow [this guide](https://maven.apache.org/resolver/maven-resolver-named-locks/analyzing-lock-issues.html) and add these system properties:

```
-Dorg.slf4j.simpleLogger.showThreadName=true
-Dorg.slf4j.simpleLogger.log.org.eclipse.aether=trace
```

Also try, independent from this, whether the `static` name mapper does solve this. if yes, the not the locking is the problem, but the lock name and we need to figure out why.

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), WDYT?

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

> Just checked the source code, all calls to the Manager are fully wrapped in sync context.

I just stepped through the stacktrace and I can't see anything that looks like a "sync context" can you explain what this is?

 

```java
Caused by: java.nio.file.AccessDeniedException: C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories.15650462061630955031.tmp -> C:\Users\runneradmin\.m2\repository\com\google\code\gson\gson\2.10.1\_remote.repositories
    at sun.nio.fs.WindowsException.translateToIOException (WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException (WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move (WindowsFileCopy.java:317)
    at sun.nio.fs.WindowsFileSystemProvider.move (WindowsFileSystemProvider.java:293)
    at java.nio.file.Files.move (Files.java:1432)
    at org.eclipse.aether.util.FileUtils$2.move (FileUtils.java:121)
    at org.eclipse.aether.util.FileUtils.writeFile (FileUtils.java:192)
    at org.eclipse.aether.util.FileUtils.writeFile (FileUtils.java:152)
    at org.eclipse.aether.internal.impl.DefaultTrackingFileManager.update (DefaultTrackingFileManager.java:108)
    at org.eclipse.aether.internal.impl.EnhancedLocalRepositoryManager.addRepo (EnhancedLocalRepositoryManager.java:274)
    at org.eclipse.aether.internal.impl.EnhancedLocalRepositoryManager.addArtifact (EnhancedLocalRepositoryManager.java:252)
    at org.eclipse.aether.internal.impl.EnhancedLocalRepositoryManager.add (EnhancedLocalRepositoryManager.java:225)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.evaluateDownloads (DefaultArtifactResolver.java:680)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:592)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:478)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:278)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:255)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:296)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:197)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:413)
```

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

Here is the build output with the additional log output:

https://github.com/eclipse-platform/eclipse.platform/actions/runs/4223999154/jobs/7334396457

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Here it is:

```java
    public List<ArtifactResult> resolveArtifacts( RepositorySystemSession session,
                                                  Collection<? extends ArtifactRequest> requests )
            throws ArtifactResolutionException
    {
        requireNonNull( session, "session cannot be null" );
        requireNonNull( session, "session cannot be null" );
        try ( SyncContext syncContext = syncContextFactory.newInstance( session, false ) )
        {
            Collection<Artifact> artifacts = new ArrayList<>( requests.size() );
            for ( ArtifactRequest request : requests )
            {
                if ( request.getArtifact().getProperty( ArtifactProperties.LOCAL_PATH, null ) != null )
                {
                    continue;
                }
                artifacts.add( request.getArtifact() );
            }

            syncContext.acquire( artifacts, null );

            return resolve( session, requests );
        }
    }
```

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

At least there is a 

```java
DefaultSyncContextFactory
```

 that simply do nothing... don't know if there might be a chance a plugin gets this one injected?

 

Beside that I think there is a potential race if one thread resolves the main artifact and the other resolves the source (or javadoc or ...) then both resolve operation still compete to the same  _remote.repositories file, what seems a possible case here ... so my point still stands that actually there is no guarantee that the process has acquired exclusive r/w access to that _remote.repositories file even if it might has exclusive access to the passed artifacts...

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Can you (or anyone) reproduce this on "normal" instance, like some windows workstation?

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) many thanks for your detailed analysis!

I think this should really be reported to JDK as it seems to hurt many projects with a lot of hacks and workarounds (that's as you have proven probably don't work at all)!

For Resolver, I think the idea is that if the process is killed "in the middle" we do not leave a half written garbage file, for that case I wonder if a simple delete-then-move won't work equally good, atomic file operations sound good at the first place but are hard to guarantee as we see here.

So there are some strategies:
* You can (as suggested) just write directly to the file and make the read more robust, and simply discard data in the case something goes wrong (I think that's always good, because error can happen always but one should be able to recover from them)
* Additionally if one wants can use some rolling file strategy, instead of writing to _remote.repositories you write to _remote.\<n>.repositories where \<n> is incremented on each write, so the process is then: find current index > write to temp > rename file to next index > delete last index ... but thats probably a way to much here as it also has impact on reading to find the current valid index

So I would most probably go for (1) here the worst that can happen is that resolver the file is not up-to-date and download it again, something that would also happen if the file was deleted by the user or maybe an request to update it ... so its actually something that can already be handled and only should happen if previously something gone wrong in which case it might be better to start fresh anyways.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

The delete-then-move approach does not work. I tried this from Tamás' PR and it fails as well. Look at the JDK code, as written, it does `DeleteFile`, then `MoveFileEx`, same issue happens.

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), I need to try the current on BSD as well today/tomorrow.

We need to try the simplest possible Java application which write within short periods to the same file serially with move atomic and make it fail. This would be good enough to make it for a report.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi), interesting:

```java
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

public class AtomicMove {

	public static void main(String[] args) throws IOException, InterruptedException {

		Path target = Paths.get("mumu");

		for (int i = 0; i < 100; i++) {
			Path temp = Paths.get("mumu." + i);
			try (Writer w = Files.newBufferedWriter(temp)) {
				w.write("I was made for crashing your, baby!");
			}
			Files.move(temp, target, StandardCopyOption.ATOMIC_MOVE);
		}
	}

}
```

with

```
Exception in thread "main" java.nio.file.AccessDeniedException: mumu.41 -> mumu
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at com.siemens.sb.sso.example.AtomicMove.main(AtomicMove.java:21)
```

On

```
$ uname -a
FreeBSD deblndw011x.ad001.siemens.net 12.4-STABLE FreeBSD 12.4-STABLE 1279c260c GENERIC  amd64
```

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), please try on Fedora, it won't be diferent.

What am I supposed to say for Windows?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Another Windows test:

```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

import com.sun.jna.platform.win32.Kernel32;
import com.sun.jna.platform.win32.WinBase;
import com.sun.jna.platform.win32.WinDef.DWORD;

public class AtomicMove {

	public static void main(String[] args) throws IOException, InterruptedException {

		Path target = Paths.get("mumu");

		for (int i = 0; i < 100; i++) {
			Path temp = Paths.get("mumu." + i);
			try (Writer w = Files.newBufferedWriter(temp)) {
				w.write(i + ": I was made for crashing you, baby!");
			}
			//Files.move(temp, target, StandardCopyOption.ATOMIC_MOVE);
			Kernel32.INSTANCE.MoveFileEx( temp.toAbsolutePath().toString(), target.toAbsolutePath().toString(),
					new DWORD( WinBase.MOVEFILE_REPLACE_EXISTING | WinBase.MOVEFILE_WRITE_THROUGH ) );
			try (BufferedReader r = Files.newBufferedReader(target)) {
				System.out.println(r.readLine());
			}
		}
	}

}
```

Output:

```
0: I was made for crashing you, baby!
1: I was made for crashing you, baby!
2: I was made for crashing you, baby!
3: I was made for crashing you, baby!
4: I was made for crashing you, baby!
5: I was made for crashing you, baby!
6: I was made for crashing you, baby!
7: I was made for crashing you, baby!
8: I was made for crashing you, baby!
9: I was made for crashing you, baby!
10: I was made for crashing you, baby!
11: I was made for crashing you, baby!
12: I was made for crashing you, baby!
13: I was made for crashing you, baby!
14: I was made for crashing you, baby!
15: I was made for crashing you, baby!
16: I was made for crashing you, baby!
17: I was made for crashing you, baby!
18: I was made for crashing you, baby!
19: I was made for crashing you, baby!
20: I was made for crashing you, baby!
21: I was made for crashing you, baby!
22: I was made for crashing you, baby!
23: I was made for crashing you, baby!
24: I was made for crashing you, baby!
25: I was made for crashing you, baby!
26: I was made for crashing you, baby!
27: I was made for crashing you, baby!
28: I was made for crashing you, baby!
29: I was made for crashing you, baby!
30: I was made for crashing you, baby!
31: I was made for crashing you, baby!
32: I was made for crashing you, baby!
33: I was made for crashing you, baby!
34: I was made for crashing you, baby!
35: I was made for crashing you, baby!
36: I was made for crashing you, baby!
37: I was made for crashing you, baby!
38: I was made for crashing you, baby!
39: I was made for crashing you, baby!
40: I was made for crashing you, baby!
41: I was made for crashing you, baby!
42: I was made for crashing you, baby!
43: I was made for crashing you, baby!
44: I was made for crashing you, baby!
45: I was made for crashing you, baby!
46: I was made for crashing you, baby!
47: I was made for crashing you, baby!
48: I was made for crashing you, baby!
49: I was made for crashing you, baby!
50: I was made for crashing you, baby!
51: I was made for crashing you, baby!
52: I was made for crashing you, baby!
53: I was made for crashing you, baby!
54: I was made for crashing you, baby!
55: I was made for crashing you, baby!
56: I was made for crashing you, baby!
57: I was made for crashing you, baby!
58: I was made for crashing you, baby!
59: I was made for crashing you, baby!
60: I was made for crashing you, baby!
61: I was made for crashing you, baby!
62: I was made for crashing you, baby!
63: I was made for crashing you, baby!
64: I was made for crashing you, baby!
65: I was made for crashing you, baby!
66: I was made for crashing you, baby!
67: I was made for crashing you, baby!
68: I was made for crashing you, baby!
69: I was made for crashing you, baby!
70: I was made for crashing you, baby!
71: I was made for crashing you, baby!
72: I was made for crashing you, baby!
73: I was made for crashing you, baby!
74: I was made for crashing you, baby!
75: I was made for crashing you, baby!
75: I was made for crashing you, baby!
77: I was made for crashing you, baby!
78: I was made for crashing you, baby!
79: I was made for crashing you, baby!
80: I was made for crashing you, baby!
81: I was made for crashing you, baby!
82: I was made for crashing you, baby!
83: I was made for crashing you, baby!
84: I was made for crashing you, baby!
85: I was made for crashing you, baby!
86: I was made for crashing you, baby!
87: I was made for crashing you, baby!
88: I was made for crashing you, baby!
89: I was made for crashing you, baby!
90: I was made for crashing you, baby!
91: I was made for crashing you, baby!
92: I was made for crashing you, baby!
93: I was made for crashing you, baby!
94: I was made for crashing you, baby!
95: I was made for crashing you, baby!
96: I was made for crashing you, baby!
97: I was made for crashing you, baby!
98: I was made for crashing you, baby!
99: I was made for crashing you, baby!
```

There are a few leftover tempfiles, but the content has arrived.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Played with the size, went upto 10 MB, no change. So it is not the size, but I guess rather the frequency.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Here it is: https://github.com/apache/maven-resolver/pull/259

I'll try to report this issue next week to the OpenJDK nio team.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Reported: https://mail.openjdk.org/pipermail/nio-dev/2023-February/013252.html

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been addressed under the conditions described in MRESOLVER-331. A true solution can only come from the OpenJDK team.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Issue logged: https://bugs.openjdk.org/browse/JDK-8303225

**Comment by jira-importer** [comment]
**[Uwe Schindler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thetaphi)** commented

Hi,
the Lucene team knows this issue, but due to our 2-phase-commits we have put a lot of thought to get the transactional system running correctly. The issue here is in fact not limited to Windows. When testing on Linux with e.g., the ext4 filesystem, the underlying problem is not necesarily showing up, because ext4 has a workaround for badly written appplications. Of course on Linux you won't get an AccessDeniedException as Linux can overwrite files that are currently open or in use.

https://www.kernel.org/doc/Documentation/filesystems/ext4.txt

> auto_da_alloc: Many broken applications don’t use fsync() when replacing existing files via patterns such as fd = open(“foo.new”)/write(fd,..)/close(fd)/ rename(“foo.new”, “foo”), or worse yet, fd = open(“foo”, O_TRUNC)/write(fd,..)/close(fd). If auto_da_alloc is enabled, ext4 will detect the replace-via-rename and replace-via-truncate patterns and force that any delayed allocation blocks are allocated such that at the next journal commit, in the default data=ordered mode, the data blocks of the new file are forced to disk before the rename() operation is committed. This provides roughly the same level of guarantees as ext3, and avoids the “zero-length” problem that can happen when a system crashes before the delayed allocation blocks are forced to disk.

So the correct way how to do this type of stuff is to fsync the newly created file and after that rename it.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

interesting, thank you Uwe. I will try that and let you know. That isn't obvious. As far as I understand `fsync()` can also kill performance. since those tracking files are written very often we need to take a look how much the impact could be, but that massive depends on OS, H/W, FS, etc.

**Comment by jira-importer** [comment]
**[Robert Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rcmuir)** commented

From https://thunk.org/tytso/blog/2009/03/15/dont-fear-the-fsync/#a-nameatomicity-not-durabilityathe-atomicity-not-durability-argument

> remember, fsync() doesn’t create extra I/O’s, although it may introduce latency as the application waits for some of the pending I/O’s to complete.

From my understanding of your email, this is the behavior you want.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Tried https://issues.apache.org/jira/browse/MRESOLVER-325?focusedCommentId=17693625&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17693625 on my desktop and did not error out. it is Fedora 37 (home is Btrfs).

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Same test ran on external SSD w/ ext4, again, no error even with increasing the number in code.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Robert Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rcmuir), [uschindler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=uschindler), the approach would be open/write/fsync/close/rename?

**Comment by jira-importer** [comment]
**[Robert Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rcmuir)** commented

additionally we fsync the file's containing directory after the rename to ensure rename is really visible. But this isn't related to your windows problem, just something you should do on *nix if you really care about the data. If you want to do that too, you may want to see lucene's helper method, since jdk does not support fsyncing directories on windows (maybe windows has synchronous metadata or something and it makes no sense to do this, i can't remember)

https://github.com/apache/lucene/blob/70c152bf321f20c589f1e002fa01ccbfc74aa398/lucene/core/src/java/org/apache/lucene/util/IOUtils.java#L408-L444

**Comment by jira-importer** [comment]
**[Robert Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rcmuir)** commented

Another trap to look out for with java, if you are going to write/fsync/close, make sure the write() really happens first. You may have to call BufferedWriter.flush or similar methods.

In lucene we write files with open/write/close. data is then in "uncommitted state" (we have some features "NRT search" that still allow you to search it in this state, kinda like read-uncommitted with a database).

When you call commit(), then we do open+fsync+close on all the data files (see that IOUtils helper, that's what it does). Then we rename() the commit marker and open+fsync+close the containing directory (again via IOUtils helper).

Sorry, i know its confusing as hell. synchronizing data to disk should be easy. But java makes it pretty hard. Write once, test everywhere.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Robert Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rcmuir), thank you very much. This is truly valuable information for us.

**Comment by jira-importer** [comment]
**[Robert Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rcmuir)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) no problem. Sorry I don't understand the bigger picture, but happy to help more if I can. I read a little on the issue and saw mentions of locking and became a little afraid :)

As someone who hasn't looked at the code, but just the file structure, I'd high-level naively try to do something like this for this artifact:

```
$ ls org/apache/maven/maven-core/3.1.1
maven-core-3.1.1.jar  maven-core-3.1.1.jar.sha1  maven-core-3.1.1.pom  maven-core-3.1.1.pom.sha1  _remote.repositories
```

1. first create org/apache/maven/maven-core file tree. Fsync parent directories of each new one i make when i do it. I'm assuming if this filetree is empty, it won't cause harm at read time.
2. next create org/apache/maven/maven-core/.tmpXYZ123 temporary to stage my files. I'm assuming these tempdirs can be filtered out by reads, so that no uncommitted stuff is really "visible" to maven.
3. next write each one of my files (jars and poms and sha1s and _remote.repositories) into org/apache/maven/maven-core/.tmpXYZ123
4. fsync all my files, including .tmpXYZ13 directory.
5. rename org/apache/maven/maven-core/.tmpXYZ123 to org/apache/maven/maven-core/3.1.1. don't use REPLACE_EXISTING. Use ATOMIC_MOVE and handle the exception if another process beat you to it.
6. fsync org/apache/maven/maven-core

If the maven code supports deleting artifacts (i dont know if this is allowed), i'd ATOMIC_MOVE 3.1.1 to .tmpABC234, then fsync org/apache/maven/maven-core/, then actually delete stuff. This way it is "atomically deleted".

The idea here would be, to avoid relying on filesystem locks at all, instead only solely "publish" or "unpublish" data via move(ATOMIC_MOVE). And since files are only written to temp directories, they can all be created with e.g. `Files.newOutputStream(path, CREATE_NEW)` and so on.
