### ISSUE TITLE
[MRESOLVER-362] NoSuchFileException moving .tmp to .jar

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#1038]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** opened **[MRESOLVER-362](https://issues.apache.org/jira/browse/MRESOLVER-362?redirect=false)** and commented

It looks like MRESOLVER-290 broke our metadata verification tests. We have a test that uses the resolver API to collect a bunch of dependencies, and checking the state is correct. Since the upgrade to 1.9 we get this

```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.boot:spring-boot-starter:jar:3.0.8-20230525.115211-13 from/to spring-snapshots (https://repo.spring.io/snapshot): /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar.4959477968260906889.tmp -> /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:44)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:448)
	... 45 more
Caused by: java.nio.file.NoSuchFileException: /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar.4959477968260906889.tmp -> /var/folders/46/2wr2nf9x0nzd1220xfnp1nzr0000gn/T/metadata-validation-m28912614894186841938/org/springframework/boot/spring-boot-starter/3.0.8-SNAPSHOT/spring-boot-starter-3.0.8-20230525.115211-13.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:416)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.eclipse.aether.util.FileUtils$2.move(FileUtils.java:108)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:500)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
```

The test is here https://github.com/spring-io/start.spring.io/tree/main/start-site-verification/src/test/java/io/spring/start/site

---

**Affects:** 1.9.10

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

If you want to give it a try with the latest state, make sure to revert 1ed8af5 as I've downgraded to 1.8 in the meantime.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I would highly prefer a sample project with npm and and the rat load comes with it. Fails for me:

```
[INFO] warning " > react-markdown@8.0.7" has unmet peer dependency "@types/react@>=16".
[INFO] error An unexpected error occurred: "ENOSYS: function not implemented, copyfile '/net/home/osipovmi/.cache/yarn/v6/npm-make-dir-2.1.0-5f0310e18b8be898cc07009295a30ae41e91e6f5-integrity/node_modules/make-dir/index.d.ts' -> '/var/osipovmi/Projekte/start.spring.io/start-client/node_modules/@babel/cli/node_modules/make-dir/index.d.ts'".
[INFO] error An unexpected error occurred: "ENOSYS: function not implemented, copyfile '/net/home/osipovmi/.cache/yarn/v6/npm-make-dir-2.1.0-5f0310e18b8be898cc07009295a30ae41e91e6f5-integrity/node_modules/make-dir/index.d.ts' -> '/var/osipovmi/Projekte/start.spring.io/start-client/node_modules/@babel/cli/node_modules/make-dir/index.d.ts'".info If you think this is a bug, please open a bug report with the information provided in "/var/osipovmi/Projekte/start.spring.io/start-client/yarn-error.log".
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for start.spring.io 0.0.1-SNAPSHOT:
[INFO]
[INFO] start.spring.io .................................... SUCCESS [  0.819 s]
[INFO] start.spring.io client ............................. FAILURE [  9.644 s]
[INFO] start.spring.io website ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Was there some transport error involved here? Any peculiarity?

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

I've created a sample that is based on our test. The only reference to Spring is a utility to delete temporary directories so it shouldn't matter:
https://github.com/snicoll-scratches/MRESOLVER-362

I can make it fail with the error above consistently. Switching to `1.8.2` and the error goes away:

```
./mvnw test -Dmaven-resolver.version=1.8.2
```

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

I was able to build, but have various (not reported) test issues, but as I see, they stem from environment, like tests are picking up my maven env? (settings.xml)

Retrying by "resetting" env (I used mvn -s settings.xml but seems my home .m2/settings.xml did mixed in)

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Ah, reproducer. Cool, thanks!

And got it:

```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud:spring-cloud-contract-stub-runner:jar:4.0.3 from/to central (https://repo1.maven.org/maven2): /tmp/metadata-validation-m21381670704345357113/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-cloud-contract-stub-runner-4.0.3.jar.14276559978813913918.tmp -> /tmp/metadata-validation-m21381670704345357113/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-cloud-contract-stub-runner-4.0.3.jar
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:44)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:448)
    ... 76 more
Caused by: java.nio.file.NoSuchFileException: /tmp/metadata-validation-m21381670704345357113/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-cloud-contract-stub-runner-4.0.3.jar.14276559978813913918.tmp -> /tmp/metadata-validation-m21381670704345357113/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-cloud-contract-stub-runner-4.0.3.jar
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:416)
    at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
    at java.base/java.nio.file.Files.move(Files.java:1432)
    at org.eclipse.aether.util.FileUtils$2.move(FileUtils.java:108)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:500)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
    ... 79 more
 
```

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

So far, to me it seems is bug in your JarSkippingTransportFactory, it violates API contract. The reproducer passes OK when I comment out these lines:

https://github.com/snicoll-scratches/MRESOLVER-362/blob/main/src/main/java/com/example/mresolver362/DependencyResolver.java#L250-L252

For ref, I have locally this:

```
          @Override
          public void get(GetTask task) throws Exception {
//           if (task.getLocation().getPath().endsWith(".jar")) {
//              return;
//           }
             this.delegate.get(task);
          } 
```

Problem occurs later, as from debug logs (thanks for setting that up!) it becomes apparent, that resolver NEVER asks for JAR, but does these two requests:

GET https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-cloud-contract-stub-runner-4.0.3.jar.sha1 (receives 404)

GET https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-cloud-contract-stub-runner-4.0.3.jar.md5 (receives 404)

Then it reports validation error (as validation is WARN, so is reported and it goes on)

```
 2023-05-26 10:31:11,049 WARN [main] o.e.a.i.i.WarnChecksumPolicy [WarnChecksumPolicy.java : 35] -- Could not validate integrity of download from https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-contract-stub-runner/4.0.3/spring-clou
d-contract-stub-runner-4.0.3.jar
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
        at org.eclipse.aether.internal.impl.AbstractChecksumPolicy.onNoMoreChecksums(AbstractChecksumPolicy.java:63)
```

and finally it arrives here: https://github.com/apache/maven-resolver/blob/maven-resolver-1.9.10/maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java#L500

Now, the problem is, that at this point, code expected: that "main payload" is downloaded, as transport did not throw anything (it was just return). This is violation of transport contract.

https://github.com/apache/maven-resolver/blob/maven-resolver-1.9.10/maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/transport/Transporter.java#L74-L81

No, as I see, you want POMs only? Or even only GAs? Or this is just for demo purposes?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I can reproduce it as well.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Created change proposal (but unsure about actual use case) https://github.com/snicoll-scratches/MRESOLVER-362/pull/1
