### ISSUE TITLE
[MRESOLVER-372] Sporadic AccessDeniedEx on Windows

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#1049]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** opened **[MRESOLVER-372](https://issues.apache.org/jira/browse/MRESOLVER-372?redirect=false)** and commented

Preambulum: original issue is not related to locking at all, is about change done in 1.9 where file processor was altered to use nio2 atomic move. Reason was to prevent possibility of partial download being read by other process (and prevent incomplete files in case of crash). Seems windows (or java on windows) have issues with atomic fs ops, causing sporadic (still unsure why) AccessDeniedExceptions. Below is original issue description as reported:

 

```java
 Caused by: java.nio.file.AccessDeniedException: xxx-SNAPSHOT.jar.15463549870494779429.tmp -> xxxx-SNAPSHOT.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
        at java.base/java.nio.file.Files.move(Files.java:1432)
        at org.eclipse.aether.util.FileUtils$2.move(FileUtils.java:108)
        at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:96)
        at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:88)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.getFile(DefaultArtifactResolver.java:490)
        ... 30 more
```

 

My suggestion would be that resolver simply uses the temp file if it can't be moved to final location and marks it as delete on exit. Even though this is not optimal, it at least ensures the the build does not fail to the cost that next time the file needs to be downloaded again.

---

**Issue Links:**
- [MINSTALL-194](https://issues.apache.org/jira/browse/MINSTALL-194) Fail to install snapshot artifact when clean phase is used

- [MRESOLVER-325](https://issues.apache.org/jira/browse/MRESOLVER-325) [REGRESSION] Suddenly seeing I/O errors under windows aborting the build

**Remote Links:**
- [GitHub Pull Request #364
](https://github.com/apache/maven-resolver/pull/364)
- [GitHub Pull Request #365
](https://github.com/apache/maven-resolver/pull/365)

**Backported to:** [2.0.0-alpha-3](https://github.com/apache/maven-resolver/milestone/77?closed=1), [1.9.17](https://github.com/apache/maven-resolver/milestone/11?closed=1)

0 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

See also MRESOLVER-325 for explanation.

**Comment by jira-importer** [comment]
**[Delany](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=delany)** commented

Can happen at the end of a large deployAtEnd build (on CI machine)

```java
09:46:47  [INFO] Retrying deployment attempt 3 of 3
...
09:50:10  Caused by: java.nio.file.AccessDeniedException: maven-metadata-xxxx-snapshots.xml.12223878285861141839.tmp -> maven-metadata-xxxx-snapshots.xml
09:50:10      at sun.nio.fs.WindowsException.translateToIOException (WindowsException.java:89)
09:50:10      at sun.nio.fs.WindowsException.rethrowAsIOException (WindowsException.java:103)
09:50:10      at sun.nio.fs.WindowsFileCopy.move (WindowsFileCopy.java:309)
09:50:10      at sun.nio.fs.WindowsFileSystemProvider.move (WindowsFileSystemProvider.java:292)
09:50:10      at java.nio.file.Files.move (Files.java:1422)
09:50:10      at org.eclipse.aether.util.FileUtils$2.move (FileUtils.java:108)
09:50:10      at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:500)
09:50:10      at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:414)
09:50:10      at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:215)
09:50:10      at org.eclipse.aether.internal.impl.DefaultDeployer.upload (DefaultDeployer.java:367)
09:50:10      at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:238)
09:50:10      at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:201)
09:50:10      at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:392)
09:50:10      at org.apache.maven.plugins.deploy.AbstractDeployMojo.deploy (AbstractDeployMojo.java:139)
09:50:10      at org.apache.maven.plugins.deploy.DeployMojo.deployAllAtOnce (DeployMojo.java:251)
09:50:10      at org.apache.maven.plugins.deploy.DeployMojo.execute (DeployMojo.java:218) 
```

Maven 3.9.3

-Daether.syncContext.named.factory=file-lock
-Daether.syncContext.named.nameMapper=file-gav

**Comment by jira-importer** [comment]
**[Rich DiCroce](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rdicroce)** commented

I've been investigating why the most recent versions of Eclipse throw errors when trying to update snapshots, and ended up here. IMO this problem can only be properly fixed by changes to Maven Resolver, but the situation is complicated. It's important to note that the rest of what I write is about the exception posted in the original description of this issue. The exception posted by Delany in the comment above is NOT the same issue.

The top-level problem is that Eclipse has an open handle to the JAR file. On Windows, this prevents the file from being replaced. So we start going down the rabbit hole. Why does Eclipse have an open handle to the JAR file? I found that there are at least three separate answers:
1. m2e loads Maven plugins so they can be executed during builds
2. Eclipse JDT loads the project's dependencies if annotation processing is enabled
3. PMD Eclipse Plugin also loads the project's dependencies if "Enable using Java Project Build Path" is enabled

But all three of these boil down to the same problem: they need to construct a URLClassLoader so they can load classes from the JARs. The classloader is the thing that is actually holding the open handle.

Okay, so the problem could be solved by not holding on to the classloader. Except that's probably not feasible. An IDE needs to support incremental compilation. That means state needs to be retained between builds, which could mean that the classloader can't just be discarded.

Well then, maybe the classloader itself could be changed to not hold open references to the JARs? That seems like it could cause all sorts of havoc if a JAR was replaced, and some classes are loaded from the old JAR and some classes get loaded from the new JAR. I doubt the JDK maintainers would be willing to accept a change like that.

Okay, so we have to hold on to the classloader and the classloader has to hold on to the JARs. What if we just copied the JARs to some temp directory? Well, we could do that... but then every single part of the IDE that needs to load the project's plugins or dependencies has to implement that. That could be a lot of changes in a lot of places. And if any part of the IDE doesn't do that, the problem comes back and is very painful to locate.

Which brings us to the conclusion I arrived at: the right solution is to just not replace the JARs at all. So I started digging through the Maven Resolver code and found the aether.artifactResolver.snapshotNormalization option. When this option is enabled (which is the default), Maven Resolver first downloads a new snapshot to a timestamped JAR file, then copies that JAR to the -SNAPSHOT file.

Okay, so we just need to disable that option and our problem is solved! Except it's not. For one thing, locally built JARs are always written to the -SNAPSHOT file. So if you have two Eclipse workspaces open, and you're building a JAR in one workspace that is needed by the other workspace, you're still going to have the same problem. Secondly, from reading the code, it looks like Maven Resolver always looks for the -SNAPSHOT file first, precisely because that's where a locally built JAR is always installed. So if we turn off normalization and we already have a -SNAPSHOT file, then we'll never actually use any new snapshots we download from a server.

That brings us to my proposed solution: the -SNAPSHOT file must die. Instead, all snapshot JARs must have timestamped filenames so that the JAR files are always immutable. Achieving this requires some big changes though:
* maven-install-plugin would need an option to install timestamped snapshots. For backwards compatibility, this would have to be off by default.
* Maven Resolver would need to deal with timestamped, locally-built snapshots. It would also have to deal with -SNAPSHOT files written by older versions, which probably means changing the way it decides which snapshot to use. Perhaps it could look at all the eligible snapshots and use the one with the newest file modification time. (Of course, then you're depending on the system clock to be sane, which isn't great either.)

I'm not an expert on any of the internals here, so there may be other headaches I haven't thought of. Even if we can get consensus on how to fix this, I don't have time to work on it right now. I've already spent more time investigating this than I should have. But I figured it was worth it to document my findings so someone else can take a crack at it.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

As far as I remember, Maven Install Plugin delegates the installation to Resolver as well..

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

This is very cool! Thank you for your investigation, time and "thought experiments", i really like them.

Yes, snapshot normalization (the thing that copies the latest downloaded TIMESTAMPED snapshot to -SNAPSHOT in local repository) is probably the culprit, and IF maven local repository could have immutable files (like releases are), it would be the simplest. Ideally, am keen to wild experiments even to make local repo CAS-like (content addressable storage), but to achieve that, we must "herd" all the code (authors) to strictly adhere and use Resolver APIs to figure out where the artifact belonging file is, and we still struggle with ancient codebases running in Maven...

I think "maven resolver dealing with which timestamped snapshot to use" is doable even without depending on local clock, but I see a bigger problem "all the rest of the world", that as I said, have copy-pasted code and assume local repo layout and so on...

A big :thumbsup: for this comment.

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

I think one should not deny such feature because there might be others that using it currently wrong. Using timestamped snapshots seems good solution here.

**Comment by jira-importer** [comment]
**[Rich DiCroce](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rdicroce)** commented

Tamas, you read my mind. :)

Making the cache CAS-like could be handy. Early drafts of the SLSA spec required content-addressable caches for levels 3 and 4, but it looks like the final draft removed that. Probably because it was infeasible due to the popularity of build systems like Maven that don't currently comply with it. But as you said, making a change that large could be a problem for other code that assumes Maven caches are laid out in a particular way. That's why I suggested to just use timestamped files, since that's a smaller change that's less likely to break things.

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

Also occurs when multiple process use the same local repository.
Eg in exec-maven-plugin ITs are executed in parallel, and error is:

```
Caused by: java.nio.file.AccessDeniedException: D:\a\exec-maven-plugin\exec-maven-plugin\target\local-repo\org\apache\maven\shared\maven-shared-utils\0.1\maven-shared-utils-0.1.pom.15783817563503912351.tmp -> D:\a\exec-maven-plugin\exec-maven-plugin\target\local-repo\org\apache\maven\shared\maven-shared-utils\0.1\maven-shared-utils-0.1.pom
    at sun.nio.fs.WindowsException.translateToIOException (WindowsException.java:83)
    at sun.nio.fs.WindowsException.rethrowAsIOException (WindowsException.java:97)
    at sun.nio.fs.WindowsFileCopy.move (WindowsFileCopy.java:301)
    at sun.nio.fs.WindowsFileSystemProvider.move (WindowsFileSystemProvider.java:287)
    at java.nio.file.Files.move (Files.java:1395)
    at org.eclipse.aether.util.FileUtils$2.move (FileUtils.java:108)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:500)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:414)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:260)
```

do we have re-try option here?

https://github.com/mojohaus/exec-maven-plugin/actions/runs/6603309437/job/18457179181?pr=384

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

[sjaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sjaranowski) as I really like to see this fixed ( [Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas) **please help here** ) as this makes maven 3.9 unusable in so many cases under windows, for a maven plugin there is a small little chance to mitigate this by using

```
try (SyncContext syncContext = syncContextFactory.newInstance(repositorySession, false)) {
    Set<Artifact> lockList = new HashSet<>();
    ... add all interesting artifacts here ...
    syncContext.acquire(lockList, null);
    ... do something with it ...
}
```

of course this is not suitable for any other third party app (e.g. IDE) outside maven that might accessing files from the local repo.

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

Next case - I think connected: https://github.com/apache/maven-mvnd/issues/862

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

The more I read about the issue "atomic file move on windows" (and related) am more and more inclined to say that "atomic move" on Windows is like Russian roulette: sometimes it works, sometimes not.

The strange thing to me is this: in local repository, release artifacts are immutable, snapshots are also (sans the "snapshot normalization" also reported, but that can be tuned in resolver, see config), and the per-definitionem mutable files are metadata files, but NOBODY reported this issue for metadata files! (one possible reason: they are not kept open by IDEs, but are "one time read" and processed, most probably).

Other thing: this is NOT in whatsoever relation to "locking" introduced in 1.9.x, actually to me this seems totally unrelated to it. Resolver does NOT lock artifact files (!), it does use "parallel hierarchy" to implement "mutual exclusive advisory locking" (so other mvn 3.9 will go for those "parallel" paths and mutually exclude).

This is all about "atomic move" Java support on Windows, as related code have only one change: old resolver (1.8 and before) did the good old "copy+delete src" using pre-nio2, while resolver 1.9 insist on "Files.move(atomic)" but the only reason for that is to prevent other processes to read partially written files....

Am still looking, but anyone having any idea, shoot!

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Just to shed some light what code does:
* you have some new content (ie. downloaded or built, so resolve or install case)
* the target file may or may not exists
* the code writes to tmp/random file _in same directory_ (so it is not cross FS or whatever atomic move even, it is happening within same god damn directory)
* once the file is written to tmp file, atomic rename to "final file" is done

The reason of this is to prevent other processes (maybe unaware of maven 3.9 locking) to be able to read "partially written" (ie. slow download) files, basically this is what "atomic move" is about, and why it was invented in the first place.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

For Maven 3.9 all you need is to build this https://github.com/apache/maven-resolver/pull/365
(and replace resolver in maven)

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

So, just to recap:
* this has nothing to do with locking (we do not lock artifact or metadata files)
* Pre 1.9 resolver did the very same thing, no change in this area (it also normalized snapshots and replaced files on download/install).
* The ONLY change in this respect Resolver 1.9 did is change the move operation implementation from pre-nio2 (as it was in 1.8) to nio2 + atomic (1.9).

So, my guts are telling me that the culprit is "atomic" on Windows. The reason for atomic is to prevent partially written files being read by some other process (ie IDE).

Also, according to that above, Resolver 1.8 was also normalizing snapshots and was rewriting files (if existing) on install/resolve, hence very same problems would be reported against it as well, but are not.

Hence, I am pretty sure it is "atomic" that is the culrpit of this issue... Please test the PR.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

I'd be very grateful for some feedback of those who use Windows...

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

So far as I see, the statement "Download fails if file is currently in use under windows" was true for any resolver (when on windows), even the pre-1.9 resolver did fail, it did not "forgive" or swallow IOExceptions. So this issue not that is unrelated to locking, but is "red herring" in general, as this was happening before resolver 1.9, with resolver 1.9, and will happen after it as well. Simply put, let Maven manage local repository ONLY, or, ask your OS vendor to do something about this.
