### ISSUE TITLE
[MRESOLVER-584] Jetty / JDK transport: HTTP2 GOAWAY improvement 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#1256]
**[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100)** opened **[MRESOLVER-584](https://issues.apache.org/jira/browse/MRESOLVER-584?redirect=false)** and commented

I am encountering a problem with the implementation of JDK transport using HTTP/2, specifically related to re-establishing connections after receiving a GOAWAY frame. (RFC quote below)

Just for example a nginx server with default configuration does only allow 1000 requests per connection before requiring "establishing a new connection".

This results in IOException, stopping resolution process: [^exception.log].

```java
Caused by: java.io.IOException: /10.8.2.106:51760: GOAWAY received
    at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)
    at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
    at org.eclipse.aether.transport.jdk.JdkTransporter.send(JdkTransporter.java:392)
    at org.eclipse.aether.transport.jdk.JdkTransporter.implGet(JdkTransporter.java:271)
    at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:501)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:433)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:66)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: /10.8.2.106:51760: GOAWAY received
    at jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:1009)
    at jdk.internal.net.http.Http2Connection.handleConnectionFrame(Http2Connection.java:874)
    at jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:749)
    ...
```

Related to: [How to handle HTTP/2 GOAWAY with java.net.HttpClient?](https://stackoverflow.com/a/55092354)

 

> Sets the maximum number of requests (...) that can be served through one HTTP/2 connection, after which the next client request will lead to connection closing and the need of establishing a new connection. 
> 
> -- [https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests](http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests)
> 
> [– https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests)

 

> Once sent, the sender will ignore frames sent on streams initiated by the receiver if the stream has an identifier higher than the included last stream identifier. Receivers of a GOAWAY frame MUST NOT open additional streams on the connection, although a new connection can be established for new streams.
> 
> – [RFC 7540 6.7](https://datatracker.ietf.org/doc/html/rfc7540#section-6.8)

---

**Affects:** 2.0.0-alpha-2, 2.0.0-alpha-3, 2.0.0-alpha-4, 2.0.0-alpha-5, 2.0.0-alpha-6, 2.0.0-alpha-7, 2.0.0-alpha-8, 2.0.0-alpha-9, 2.0.0-alpha-10, 2.0.0-alpha-11, 2.0.0

**Attachments:**
- [exception_jetty.log](https://issues.apache.org/jira/secure/attachment/13070110/exception_jetty.log) (_19.25 kB_)
- [exception.log](https://issues.apache.org/jira/secure/attachment/13070105/exception.log) (_25.29 kB_)

**Issue Links:**
- [MNG-8145](https://issues.apache.org/jira/browse/MNG-8145) GOAWAY received
 (_**"duplicates"**_)

**Remote Links:**
- [GitHub Pull Request #532
](https://github.com/apache/maven-resolver/pull/532)
- [GitHub Pull Request #533
](https://github.com/apache/maven-resolver/pull/533)

**Comment by jira-importer** [comment]
**[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100)** commented

HTTP/1.1 is definitely a workaround, but since I'm looking to speed up resolution by using HTTP/2, it is not an option for me.

I believe this issue is not related to concurrent requests. The problem persists even when `maxConcurrentRequests` is set to 1. It seems to be about how many requests a server allows in an HTTP/2 connection (not stream) and opening a new connection if a GOAWAY frame is received from the server.

Jetty appears to handle this differently, but it still results in an error because of GOAWAY frame from server:

```java
Could not transfer artifact com.vaadin.external.gwt:gwt-elemental:pom:2.8.2.vaadin2 from/to central-ifd (https://central.repo.maven.hq.ifd-gmbh.com/): cancel_stream_error/closing
```

[^exception_jetty.log]

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

So both HTTP/2 clients suffer from same thing...

In case of JDK transport unsure can be done anything...

In case of Jetty I hope we can improve things...

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)

We have this issue already, this is a dup.

**Comment by jira-importer** [comment]
**[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100)** commented

Certainly, MNG-8145 addresses the problem, but shouldn't there also be a ticket for the problem related to Jetty transport?

**Comment by jira-importer** [comment]
**[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100)** commented

Sure, no problem!

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100) we forgot to ask even.. do you use Maven 4? Or in other words, how you use Maven Resolver 2?

Do you want a binary? Or you can build the PR yourself?

**Comment by jira-importer** [comment]
**[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100)** commented

I tested using the latest beta release, and master of 4.0.0. I would prefere PR. (Just build a dist of the versions)

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100) I am curious about your results... Or you need something more than "just" Resolver PRs?

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Recreated reproducer from MNG-8145 (I totally missed there is one!):

maven 4.0.0-beta-3 FAILS as expected.

The https://github.com/apache/maven-resolver/pull/532 made it build successfully!

**Comment by jira-importer** [comment]
**[Paul Scholz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scholzi100)** commented

I tested with the JDK transport PR, and it appears that the JDK is not handling this correctly. https://bugs.openjdk.org/browse/JDK-8335181

It would definitely be interesting to see what happens if the server sends a GOAWAY after a PUT request. Specifically, if the server responds with GOAWAY along with headers, this could result in a failed PUT for the client but a successful one for the server.

Next will checkout Jetty transport.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

To recap: changes merged as part of this JIRA do not fix the problem (as Jdk HttpClient cannot, as it currently does not handle it). Hence the issue goal changed from "fix" to "improve", and it improves but (radically) shortening life span of HTTP2 clients, that were originally kept alive across whole duration of session, but now (as any other transport by the way) are kept alive as long as Transport is kept alive.
