### ISSUE TITLE
[MRESOLVER-55] Artifact download failures

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#790]
**[Lasse Westh-Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lassewesth)** opened **[MRESOLVER-55](https://issues.apache.org/jira/browse/MRESOLVER-55?redirect=false)** and commented

Hey,

We often run Maven builds of https://github.com/neo4j/neo4j on machines with cold caches/ empty ~/.m2/repository folders.

There are rather a lot of dependencies to download, so even though the failure rate of individual artifact downloads is small, at our scale it causes significant build failures.

I am working on seeding caches. Separately though it would be great to be able to configure retries and timeouts for dependency downloads - optimise for build throughput rather than latency as it were.

How do I do that? I can't find it documented anywhere, and trying to browse "wagon" source code got me nowhere.

Regards,

Lasse

 

---

**Affects:** Maven Artifact Resolver 1.1.1

**Issue Links:**
- [MRESOLVER-54](https://issues.apache.org/jira/browse/MRESOLVER-54) Artifact download failures
 (_**"is duplicated by"**_)
- [WAGON-526](https://issues.apache.org/jira/browse/WAGON-526) Make the retry handling of HttpClient configurable
 (_**"depends upon"**_)

1 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

It is onclear what you mean by "machines" and if you have enough control.
First thing that comes to my mind: consider using a [repository manager](https://maven.apache.org/repository-management.html), which makes it much easier to control these kind of settings.
If machine is a build server, try adding the following option by default:  `-C,--strict-checksums                  Fail the build if checksums don't match`
This will at least fail the build fast.

**Comment by jira-importer** [comment]
**[Lasse Westh-Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lassewesth)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) I am using a repository manager - Maven Central. I am just downloading things via HTTP from Maven Central, nothing exotic.

I don't see what checksums would help with. The HTTP downloads fail with e.g. status code 502. There _seems_ to be retries - I mean it is bog standard HTTP stuff innit.

I just want to have extra many retries and maybe longer timeouts because I know my problem domain: that intermittent HTTP downloads failing cause my builds to fail.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Maven Central it not **_your_** repository manager. I would expect an Archiva, Artifactory or Nexus, which is connected to Maven Central. This repository manager is installed within your infra and acts like the cache you are looking for. So your builds are not downloading direcly from Central anymore, but from this manager.

**Comment by jira-importer** [comment]
**[Lasse Westh-Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lassewesth)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) we already have a proxy cache - same deal. As soon as requests start crossing the network, there is a small failure rate. Multiplied to our scale, it is an unacceptable failure rate.

So effectively there is Maven client going to our proxy cache, which in turns goes to Maven Central CDN - and _still_ failure rates are too high. Our proxy cache improved things and we got more throughput (less builds failing due to artifact download errors) but it is still not good enough.

So in my view this is a client issue: I need my Maven client to behave more leniently, taking more retries and perhaps longer timeouts to ensure better throughput. And I am happy to pay with reduced latency.

So is this stuff configurable or not?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I'm not aware of such configuration. However, I would expect this to be a responsibility of [Maven Artifact Resolver](https://maven.apache.org/resolver/index.html) and not Wagon.

**Comment by jira-importer** [comment]
**[Lasse Westh-Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lassewesth)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) aight I have duplicated the bug over there: https://issues.apache.org/jira/browse/MRESOLVER-54

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Log files please. I haven't seen anything confirming a bug in Aether or Wagon. Even if, I consider it to be in Wagon.

> separately though it would be great to be able to configure retries and timeouts for dependency downloads

Wagon offers most of that and the upcoming version will cover all of them.

**Comment by jira-importer** [comment]
**[Lasse Westh-Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lassewesth)** commented

Hey [Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o),

I don't think there is a bug per se. I just want to be able to control retries because the default behaviour does not fit with my use case.

I'll dig around for some logs - things have gotten a lot better now that we employ seeded caches and thus have many fewer downloads.

**Comment by jira-importer** [comment]
**[Lasse Westh-Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lassewesth)** commented

For completeness, seeded caches was _also_ kinda clumsy: https://issues.apache.org/jira/browse/MDEP-568

But we got something working now and it made a big difference.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

You are looking for WAGON-526 as well as read and connection timeout in the HTTP config for the server in your `settings.xml`.

**Comment by jira-importer** [comment]
**[gordon cody](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gordon.cody@zafin.com)** commented

Hello Michael

We have the same problem when we need to download into an empty maven cache from our artifactory . It occurs only when our network is quite busy. We modified our maven-3.5.2 to use the new wagon-http-3.2 jars and set -Dmaven.wagon.http.retryHandler.count=4.

Apologies, but I cannot provide complete logs. With the wagon-http-3.2 jars installed, I can see **I/O retry messages** in some of the successful builds, (this is great):

org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
 I/O exception (org.apache.maven.wagon.providers.http.httpclient.NoHttpResponseException) caught when processing request to {s}->\<ourdomain>:443: The target server failed to respond
org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute Retrying request to {s}->\<ourdomain>

 

Still we are having intermittent issues although the errors are now harder to reproduce.

This page [https://maven.apache.org/wagon/wagon-providers/wagon-http/](http://example.com/) talked about standard vs default  wagons so I tried adding this to our build -Dmaven.wagon.http.retryhandler.class=standard in order to avoid having cases where retries would be skipped but the error continues to occur.

 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project xyz: Could not resolve dependencies for project \<gid>: \<artifactid>:pom:\<version>: Could not transfer artifact\<somegid>:\<someartifactid>:jar:\<someversion> from/to \<ourrepo> (\<our url>): Connect to \<ourdomain>:443 [<ourdomain>/<ourIP>] **failed: connect timed out**.

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project \<our module> Could not resolve dependencies for project \<our gid>:\<our aid>:war:\<our version>-SNAPSHOT: Could not transfer artifact \<somegid>:\<someaid>:jar:\<someversion> from/to \<our repository name> (\<our repoUrl>): Connect to \<our host>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
 at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
 at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
 at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
 at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project \<our gid>:\<our aid>:war:\<our version>-SNAPSHOT: Could not transfer artifact \<somegid>:\<someaid>:jar:\<someversion> from/to \<our repository name> (\<our repoUrl>): Connect to \<our host>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
 at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact \<failed gid>:\<failed aid>:jar:\<failed version> from/to \<our repository name> (\<our repoUrl>): Connect to \<our host>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
 at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact \<failed gid>:\<failed aid>:jar:\<failed version> from/to \<our repository name> (\<our repoUrl>): Connect to \<our host>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
 at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact \<failed gid>:\<failed aid>:jar:\<failed version> from/to \<our repository name> (\<our repoUrl>): Connect to \<our host>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
 at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
 at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.wagon.TransferFailedException: Connect to \<ourhost>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
 at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
 at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
 at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
 at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
 at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
 at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
 at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
 at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
 at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
... 4 more
Caused by: org.apache.maven.wagon.providers.http.httpclient.conn.ConnectTimeoutException: Connect to \<ourhost>:\<our port> [<our host>/<our IP>] failed: connect timed out
 at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:132)
 at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
 at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
 at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
 at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
 at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:86)
 at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
 at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
 at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
 at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
 at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
... 13 more
Caused by: java.net.SocketTimeoutException: connect timed out
 at java.net.PlainSocketImpl.socketConnect(Native Method)
 at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
 at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
 at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
 at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
 at java.net.Socket.connect(Socket.java:589)
 at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:239)
 at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
... 23 more

 

We also twice got **GET request of: <full path to jar> from <our repository> failed**

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project \<our module>: GET request of: \<some-full-jar-pathname>.jar from \<our repository> failed
 at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:363)
 at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:316)
 at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:285)
 at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
 at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
 at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
 at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
 at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
 at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
 at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
     ... 4 more
Caused by: java.net.SocketTimeoutException: Read timed out
 at java.net.SocketInputStream.socketRead0(Native Method)
 at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 at java.net.SocketInputStream.read(SocketInputStream.java:171)
 at java.net.SocketInputStream.read(SocketInputStream.java:141)
 at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
 at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
 at sun.security.ssl.InputRecord.read(InputRecord.java:532)
 at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
 at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
 at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
 at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
 at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
 at org.apache.maven.wagon.providers.http.httpclient.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
 at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
 at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:531)
 at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:353)
 ... 13 more

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[gordon cody](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gordon.cody@zafin.com), have you tried to investigate the connect timed out from your server? There must be a reason for this? Network congestion, server overload? Do you think that the error is fully on your side?

**Comment by jira-importer** [comment]
**[gordon cody](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gordon.cody@zafin.com)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) There are no errors in our artifactory.log and there is nothing in our artifactory request log except for lines with 200(OK) so I don't think the artifactory is even seeing the request that fails.  The errors happen on our CI system when multiple builds are going on so I think it is due to network congestion. Sorry, but I am not sure what you mean by "fully on your side".

In the build log just before the connect timeout occurs there is this info:

```
[12:09:36]W:         [<ourgid>:<ourartifactid>] FINE: http-outgoing-6 << Content-Length: 40
[12:09:36]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:09:36 PM org.apache.maven.wagon.providers.http.httpclient.headers onResponseReceived
[12:09:36]W:         [<ourgid>:<ourartifactid>] FINE: http-outgoing-6 << Date: Tue, 30 Oct 2018 12:08:42 GMT
[12:09:36]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:09:36 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec execute
[12:09:36]W:         [<ourgid>:<ourartifactid>] FINE: Connection can be kept alive indefinitely
[12:09:36]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:09:36 PM org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager releaseConnection
[12:09:36]W:         [<ourgid>:<ourartifactid>] FINE: Connection [id: 6][route: \{s}->https://<ourdomain>:<ourport> can be kept alive indefinitely
[12:09:36]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:09:36 PM org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager releaseConnection
[12:09:36]W:         [<ourgid>:<ourartifactid>] FINE: Connection released: [id: 6][route: \{s}->https://<ourdomain>:<ourport>][total kept alive: 3; route allocated: 4 of 20; total allocated: 4 of 40]
[12:09:36] :     [Step 2/8] [INFO] Downloaded: https://<ourdomain>:<ourport>/<full artifactory path to the jar>.jar (3806 KB at 116.0 KB/sec)
[12:10:03]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:10:03 PM org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultManagedHttpClientConnection shutdown
[12:10:03]W:         [<ourgid>:<ourartifactid>] FINE: http-outgoing-8: Shutdown connection
[12:10:03]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:10:03 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec abortConnection
[12:10:03]W:         [<ourgid>:<ourartifactid>] FINE: Connection discarded
[12:10:03]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:10:03 PM org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultManagedHttpClientConnection close
[12:10:03]W:         [<ourgid>:<ourartifactid>] FINE: http-outgoing-8: Close connection
[12:10:03]W:         [<ourgid>:<ourartifactid>] Oct 30, 2018 12:10:03 PM org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager releaseConnection
[12:10:03]W:         [<ourgid>:<ourartifactid>] FINE: Connection released: [id: 8][route: \{s}->https://<ourdomain>:<ourport>][total kept alive: 3; route allocated: 3 of 20; total allocated: 3 of 40]
[12:10:11] :     [Step 2/8] [Maven Watcher] 
[12:10:11]E:     [Step 2/8] Failed to execute goal on project <our project>: Could not resolve dependencies for project <ourgid>:<ourartifactid>:pom:<version>: Could not transfer artifact <somegid>:<someartifactid>:jar:<someversion> from/to <our repository name> (https://<ourdomain>:<ourport>/<our repository>): Connect to <ourdomain>:<ourport> [<ourdomain>/<our IP>] failed: connect timed out
```

The settings.xml contains the following:

```xml
        <httpConfiguration>
          <all>
           <connectionTimeout>60000</connectionTimeout>
            <readTimeout>60000</readTimeout>
            <usePreemptive>true</usePreemptive>
          </all>
        </httpConfiguration>
```

I dont see anything in the build log showing +any+ retries for connect.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Can we have a wireshark dump, privately? Otherwise I have to close eas `Cannot Reproduce` because we don't have access to your infrastructure.
