### ISSUE TITLE
[MRESOLVER-38] SOE/OOME in DefaultDependencyNode.accept

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#805]
**[Andreas Sewe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sewe)** opened **[MRESOLVER-38](https://issues.apache.org/jira/browse/MRESOLVER-38?redirect=false)** and commented

I noticed a `StackOverflowErrror` when trying to build the classpath for `org.webjars.npm:n3-charts:2.0.17` using Maven Resolver 1.1.0.

I’ve managed to produce a minimal example based on the `maven-resolver-demos` from the `master-with-demos` branch. To reproduce, just apply the attached patch to the branch (tried this with commit [`84a32a86`](https://github.com/apache/maven-resolver/commit/84a32a866ff27d4df75124074fd925588f4a574d)) and run the `GetDependencyTree` example:

```
------------------------------------------------------------
GetDependencyTree
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Resolving artifact org.webjars.npm:n3-charts:pom:2.0.17
Resolved artifact org.webjars.npm:n3-charts:pom:2.0.17 from central (https://repo.maven.apache.org/maven2/, default, releases+snapshots)
…
Resolving metadata org.webjars.npm:uglifycss/maven-metadata.xml from central (https://repo.maven.apache.org/maven2/, default, releases+snapshots)
Resolved metadata org.webjars.npm:uglifycss/maven-metadata.xml from central (https://repo.maven.apache.org/maven2/, default, releases+snapshots)
Resolving artifact org.webjars.npm:uglifycss:pom:0.0.18
Resolved artifact org.webjars.npm:uglifycss:pom:0.0.18 from central (https://repo.maven.apache.org/maven2/, default, releases+snapshots)
Exception in thread "main" java.lang.StackOverflowError
	at org.eclipse.aether.util.graph.visitor.PathRecordingDependencyVisitor.visitEnter(PathRecordingDependencyVisitor.java:102)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:341)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
```

(Note: The patch changes the `plexus-utils` version as well, as I was getting a `ClassNotFoundException` for `org.codehaus.plexus.util.xml.pull.EntityReplacementMap` otherwise.)

---

**Affects:** Maven Artifact Resolver 1.1.0, 1.3.3

**Attachments:**
- [maven-resolver-demos.patch](https://issues.apache.org/jira/secure/attachment/12900480/maven-resolver-demos.patch) (_1.55 kB_)

**Issue Links:**
- [MNG-5592](https://issues.apache.org/jira/browse/MNG-5592) Maven dependency resolution locks up

- [MNG-6737](https://issues.apache.org/jira/browse/MNG-6737) StackOverflowError when version ranges are unsolvable and graph contains a cycle

- [MRESOLVER-93](https://issues.apache.org/jira/browse/MRESOLVER-93) PathRecordingDependencyVisitor to handle 3 cycles
 (_**"depends upon"**_)

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Andreas Sewe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sewe)** commented

Other artifacts from `org.webjars` exhibiting the same symptoms: `org.webjars.npm:systemjs-builder:0.15.7`, `org.webjars.npm:radium:0.16.5`, `org.webjars.npm:babel-register:6.5.1`.

Maybe this helps in analyzing the situation, although I am afraid all four artifacts presumably have a rather large dependency tree, based on the number of POMs downloaded during the `collectDependencies` call.

**Comment by jira-importer** [comment]
**[Andreas Sewe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sewe)** commented

What’s **worse**: There exist artifacts for which doing a simple `collectDependencies` does not result in `StackOverflowError` but in an `OutOfMemoryError`; thus, this can kill not just one but all threads.

Using `GetDependencyTree` on `org.webjars.npm:babel-plugin-transform-class-constructor-call:6.3.13` again produces a huge stack of `DefaultDependencyNode.accept`, but with the additional problem that the constructs a huge (160k entries!) `paths` `List<List<DependencyNode>>` (counted using Eclipse MAT on a heap dump.)

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.aether.util.graph.visitor.PathRecordingDependencyVisitor.visitEnter(PathRecordingDependencyVisitor.java:108)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:341)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
…
```

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

Is this the same as MRESOLVER-93? Any chance the fix for that fixed this too?
