### ISSUE TITLE
[MRESOLVER-151] Enforce a checksum policy to be provided explicitly

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#860]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MRESOLVER-151](https://issues.apache.org/jira/browse/MRESOLVER-151?redirect=false)** and commented

This mirrors MNG-5728. The change has to happen in `DefaultChecksumPolicyProvider`.

---

**Affects:** 1.6.1

**Issue Links:**
- [MNG-5728](https://issues.apache.org/jira/browse/MNG-5728) Switch the default checksum policy from "warn" to "fail"

- [MRESOLVER-90](https://issues.apache.org/jira/browse/MRESOLVER-90) HTML content in POM: Maven should validate content before storing in local repo
 (_**"is depended upon by"**_)

**Remote Links:**
- [GitHub Pull Request #83
](https://github.com/apache/maven-resolver/pull/83)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

To me it makes sense that Maven provides a default policy for artifact-resolver, but is artifact-resolver responsible for choosing the default? I would go for IllegalArgumentException.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No, I don't think so because MNG-5728 would not work. I think Maven sets a custom policy so this one does not apply. If used outside of Maven land this is likely used. Ant Tasks.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

But then you want a policy matching a specific Maven version.
Maybe a second implementation of ChecksumPolicyProvider (Maven4ChecksumPolicyProvider)?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I wouldn't do this because Maven Resolver can live without Maven, but not the other way around. Separation of concerns. We could move this change to Maven Resolver 2.0.0 if explictily required, but I think this is OK for 1.7.0.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

All methods of https://github.com/apache/maven-resolver/blob/master/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultChecksumPolicyProvider.java provide a policy, but every unknown policy if automatically transformed to some default. I still don't like that. If I apply a  "super-strict" policy and it doesn't exist, just throw an exception. It is not up to the ChecksumPolicyProvider to just pick one (even with possible different outcome based on the version of artifact-resolver)
It that doesn't work with MNG-5728, we need to revisit that issue.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I will check that.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

OK, I have just checked both code bases. What Maven basically does is to create a `RepositoryPolicy` with `checksums` `fail`.  This value in turn is used in Resolver to query the provider for a proper `ChecksumProvider`. So there is no need to provide another provider. The defaults of Resolver only work when the caller never provides a checksum policy. So consider you are using Resolver in your custom code outside Maven land and create a repo with a default policy right now you will get warnings only. You have to configure failures explicitly. With this change your custom code will have failures immediately during transports.

Is that clear? I expect sane callers to have fail enabled by explicitly.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I think it is clear to me. So for Maven there's no need to change this, because it provides an explicit policy.
For other tools that don't provide an explicit policy (or a non-existing policy) it will now fall back to warn.
If we implement this change, if will fail instead.
As said I don't like the idea that Artifact Resolver decides the policy, that should be up to the tool using it.
Ant tasks can say: my default is warn, unless I'm onfigured to use a different policy,
With that: the IAE is still an option, right?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

> I think it is clear to me. So for Maven there's no need to change this, because it provides an explicit policy.
> For other tools that don't provide an explicit policy (or a non-existing policy) it will now fall back to warn.
> If we implement this change, if will fail instead.

Correct, if not explicitly configured, checksum failures will fail the execution.

> As said I don't like the idea that Artifact Resolver decides the policy, that should be up to the tool using it.

But Maven does too? Shouldn't we provide sane defaults? Removing default policies would be to change APIs. I think a strict default is better than a dev setting warn due to laziness.

> With that: the IAE is still an option, right?

This is a different issue. I agree that a text-based enum should not ignore invalid values by assigning them to default behavior.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

> bq. But Maven does too? Shouldn't we provide sane defaults? Removing default policies would be to change APIs. I think a strict default is better than a dev setting warn due to laziness.

AFAIK Maven always selected the valid policy. For other tools using Artifact Resolver we cannot tell.
The contract https://github.com/apache/maven-resolver/blob/master/maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumPolicyProvider.java says that policies may never be null.
However, the default implementation doesn't work like that: both null and invalid values will silently use the default, whereas both are illegal arguments to me.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Correct, that's an implemenation error. I will create new issue for that.
But this issue, is the approach acceptable?

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

Hi guys. Thanks for working on Maven.

Some feedback for you from a Maven API user: XWiki. It took us a a good part of the day to find out why XWiki is now failing with (including having to debug the maven resolver source code):

```
Unsupported policy:
class org.xwiki.extension.repository.LocalExtensionRepositoryException: Failed to save extension [com.apptasticsoftware:rssreader/3.4.0] descriptor
    at org.xwiki.extension.repository.internal.local.DefaultLocalExtensionRepository.storeExtension(DefaultLocalExtensionRepository.java:195)
    at org.xwiki.extension.job.internal.InstallJob.storeExtension(InstallJob.java:172)
    at org.xwiki.extension.job.internal.InstallJob.store(InstallJob.java:157)
    at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:126)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: class java.lang.IllegalArgumentException: Unsupported policy: 
    at org.eclipse.aether.internal.impl.DefaultChecksumPolicyProvider.validatePolicy(DefaultChecksumPolicyProvider.java:122)
    at org.eclipse.aether.internal.impl.DefaultChecksumPolicyProvider.newChecksumPolicy(DefaultChecksumPolicyProvider.java:59)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.newChecksumPolicy(BasicRepositoryConnector.java:354)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:270)
    at org.xwiki.extension.repository.aether.internal.AetherExtensionRepository.getFile(AetherExtensionRepository.java:309)
    at org.xwiki.extension.repository.aether.internal.AetherExtensionRepository.openStream(AetherExtensionRepository.java:281)
    at org.xwiki.extension.repository.aether.internal.AetherExtensionFile.openStream(AetherExtensionFile.java:54)
    at org.xwiki.extension.repository.internal.local.DefaultLocalExtensionRepository.storeExtension(DefaultLocalExtensionRepository.java:183)
    at org.xwiki.extension.job.internal.InstallJob.storeExtension(InstallJob.java:172)
    at org.xwiki.extension.job.internal.InstallJob.store(InstallJob.java:157)
    at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:126)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

This happened to us when moving the version of Maven we use as a library. It's really not great from a backward compatibility POV that Maven Resolver would change a behavior like this IMO. The reporting of the error could provide more information too.

For reference: https://github.com/xwiki/xwiki-commons/commit/067d23ddb55c2b9335eca8e6b675a54da5f43dc1

Thanks
