### ISSUE TITLE
[MRESOLVER-96] Dependency Injection fails after upgrading to Maven 3.6.2

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#875]
**[Marek Neumann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marek.neumann)** opened **[MRESOLVER-96](https://issues.apache.org/jira/browse/MRESOLVER-96?redirect=false)** and commented

When using Maven Resolver 1.4.1 in combination with Maven 3.6.2 (also 3.6.3) we face the following errors when we bootstrap our application:

```java
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:1) No implementation for org.apache.maven.model.composition.DependencyManagementImporter was bound.
  while locating org.apache.maven.model.composition.DependencyManagementImporter
    for field at org.apache.maven.model.building.DefaultModelBuilder.dependencyManagementImporter(DefaultModelBuilder.java:207)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58) (via modules: build.development.boot.Bootstrap$ResolverModule -> org.apache.maven.repository.internal.MavenResolverModule)2) No implementation for org.apache.maven.model.management.DependencyManagementInjector was bound.
  while locating org.apache.maven.model.management.DependencyManagementInjector
    for field at org.apache.maven.model.building.DefaultModelBuilder.dependencyManagementInjector(DefaultModelBuilder.java:213)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58) (via modules: build.development.boot.Bootstrap$ResolverModule -> org.apache.maven.repository.internal.MavenResolverModule)
...
17 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
```

The relevant code part is:

```java
Guice.createInjector(new ResolverModule()).getInstance(RepositorySystem.class);

static class ResolverModule extends AbstractModule {
    @Override
    protected void configure() {
        install(new MavenResolverModule());
        bind(RepositoryConnectorFactory.class).annotatedWith(Names.named("basic")).to(BasicRepositoryConnectorFactory.class);
        bind(TransporterFactory.class).annotatedWith(Names.named("file")).to(FileTransporterFactory.class);
        bind(TransporterFactory.class).annotatedWith(Names.named("http")).to(HttpTransporterFactory.class);
    }

    @Provides
    @Singleton
    Set<RepositoryConnectorFactory> provideRepositoryConnectorFactories(@Named("basic") RepositoryConnectorFactory basic) {
        Set<RepositoryConnectorFactory> factories = new HashSet<>();
        factories.add(basic);
        return Collections.unmodifiableSet(factories);
    }

    @Provides
    @Singleton
    Set<TransporterFactory> provideTransporterFactories(@Named("file") TransporterFactory file, @Named("http") TransporterFactory http) {
        Set<TransporterFactory> factories = new HashSet<>();
        factories.add(file);
        factories.add(http);
        return Collections.unmodifiableSet(factories);
    }
} 
```

This works with either maven-resolver-provider 3.6.0 or downgrading all org.apache.maven.resolver artifacts to 1.3.1.

It seems as if a similar problem occurred in Idea when setting used Maven version to 3.6.2:

https://youtrack.jetbrains.com/issue/IDEA-221882

Is this a regression introduced in one of the recent maven-resolver versions?

---

**Affects:** 1.4.1

**Issue Links:**
- [MRESOLVER-186](https://issues.apache.org/jira/browse/MRESOLVER-186) Update Maven version in Resolver Demo Snippets
 (_**"is fixed by"**_)

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Looks we missed adding Guice "Maven Model Module" while refactoring to JSR 330

Quick fix for your code oud be to manually add missing bindings

`bind( DependencyManagementImporter.class ).to( DefaultDependencyManagementImporter.class );`
`bind( DependencyManagementInjector.class ).to( DefaultDependencyManagementInjector.class );`

`...`

**Comment by jira-importer** [comment]
**[Marek Neumann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marek.neumann)** commented

Thanks for having a glance and for the workaround. We found another easier way to include the resolver without having the need for the Guice dependency. Will there be a fix in the next release for the regression with Maven >=3.6.2?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Can someone provide a PR with a test? I'be happy to merge this.

**Comment by jira-importer** [comment]
**[Marek Neumann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marek.neumann)** commented

We had to add a lot of code to make it work with Maven 3.6.2. It would be nice if it could be fixed.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz), I have updated `mavenVersion` in the mentioned POM and cannot reproduce this case. Can someone tell me how to reproduce properly?

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

In org.apache.maven.resolver.examples.util.Booter#newRepositorySystem please uncomment _GuiceRepositorySystemFactory_ and run one of examples from _maven-resolver-demo-snippets_

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz), thanks see the error now. I have no idea how this can be fixed. Never used Guice directly.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This needs to be reviewed because a lot has happened on master recently.
