### ISSUE TITLE
[MRESOLVER-298] javax.inject should be provided or optional

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver#982]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** opened **[MRESOLVER-298](https://issues.apache.org/jira/browse/MRESOLVER-298?redirect=false)** and commented

Using resolver in a non DI context and got this exception

```java
java.lang.NoClassDefFoundError: javax/inject/Provider
	at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapterFactoryImpl.getManuallyCreatedNameMappers(NamedLockFactoryAdapterFactoryImpl.java:85)
	at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapterFactoryImpl.<init>(NamedLockFactoryAdapterFactoryImpl.java:117)
	at jdk.internal.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
```

This is because javax.inject is declared as provided and/or optional whereas it's not.

Reason: 1.9.0 introduced an unintended change that made it REQUIRED. Fix is to change code to not load any Provider when it is not used in Guice/Sisu.

---

**Remote Links:**
- [GitHub Pull Request #235
](https://github.com/apache/maven-resolver/pull/235)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Did you use service locator or completely manually?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

code is here https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/tests/jetty-home-tester/src/main/java/org/eclipse/jetty/tests/hometester/JettyHomeTester.java#L248

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

SL is used :(

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/tests/jetty-home-tester/src/main/java/org/eclipse/jetty/tests/hometester/JettyHomeTester.java#L359

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Unsure why deprecated SL is being used in Jetty newly added code?
